### ISSUE TITLE
Skype icon

### ISSUE THREAD

**Issue by twsh** [xdanaux/fontawesome-latex#1]
I'm having trouble using the Skype icon. Here's an MWE that produces the problem

```
\documentclass{article}
\usepackage{fontawesome}
\begin{document}
\faGithub
\faSkype
\end{document}
```

When I do `latexmk -xelatex mwe.tex` I get the GitHub logo in the PDF as expected, but a blank rectangle where the Skype icon should be which suggests to me that the correct glyph isn't being found. I have version 4.4.0 of the Fontawesome font installed.

**Comment by carlodri** [comment]
use `pdflatex`, looks like `XeLaTeX` has issues with `fontawesome`(see issue #2)

**Comment by twsh** [comment]
With the latest versions of the package and font this is now working for me with `xelatex`.
