### ISSUE TITLE
Fontawesome 5.0 with new icons and new features

### ISSUE THREAD

**Issue by hpvd** [xdanaux/fontawesome-latex#17]
Would be awesome if one could use fontawesome 5.0 's new icons and most interesting features:-)

What's new and interesting on this for usage in Latex documents:

1. of course: more icons, see https://fontawesome.com/icons?d=gallery
2. optimized shape of each icon
3. SVG of Icons as alternative to font icons (maybe interesting on technical side of implementation)
4. "Power Transforms" https://fontawesome.com/how-to-use/svg-with-js#power-transforms
   * Scaling
   * Positioning
   * Rotating
   * Flipping
5. Masking (Background show through) https://fontawesome.com/how-to-use/svg-with-js#masking
6. Layering of several icons, text or counter (= highly optimized "stacking" (v4)) https://fontawesome.com/how-to-use/svg-with-js#layering
7. there is a pro version which bring some even more interesting things:
   * 3 different versions of each icon **which would help to match appearance of document / used fonts**
     - solid
     - regular
     - light
   * more icons

**Comment by hpvd** [comment]
To drill it down, there are 2 most interesting things:
- possibility to use the **new icons**
  * included in FA free and
  * the ones included in FA pro
- possibility to use the **different versions of an icon** (pro)
  * solid
  * regular
  * light

for this, latex package needs some kind of possibility to work with locally stored FA files
(of course FA pro package needs to be available and accessible on users computer)

**Comment by CountMurphy** [comment]
For some systems (Arch in my case) upgrading to fontawesome 5 completely breaks this package.

**Comment by zauguin** [comment]
@hpvd I do not think this package should be updated to Font Awesome 5, because this might break existing documents, especially because the aliases got removed in version 5.
Instead I uploaded a new package [fontawesome5](https://ctan.org/pkg/fontawesome5), which supports the new icons, different styles and also the Pro version.

**Comment by hpvd** [comment]
@zauguin wow making and uploading a new package especially for FA5 is of course even more awesome :-)
Many thanks for your work!!
