### ISSUE TITLE
Fontawesom icons not displayed with moderncv

### ISSUE THREAD

**Issue by Rapster** [xdanaux/fontawesome-latex#2]
Hi there!

Using 4.4.0 font-awesome package with moderncv 2.0.0 does not displayed icons. Here a sample:

```latex
\documentclass[11pt,a4paper,sans]{moderncv}
\usepackage{fontspec}
\usepackage{fontawesome}
\moderncvtheme[blue]{classic}                
\usepackage[english]{babel}
\moderncvicons{awesome}

\firstname{XXXX}
\familyname{XXXX}

\mobile{+XXX (0)XXXXXX}                    
\email{XXXXXX.XXXXXX@XXXX.com}                
\social[linkedin]{www.linkedin.com/in/XXXXX}
\social[github]{Rapster}

\begin{document}
\makecvtitle
\section{Objective}
This a pair of glass: \faGlass
\end{document}
````

It does not display icons, or you can test with "template.tex" provided in moderncv :/ I'm runnning under Miktex 2.9 and Windows 7 (64 bits)

**Comment by gaelfoppolo** [comment]
Weird. Can you get the most updated version of MikTex?
Try with pdfLaTex instead of XeLaTeX, see if anything change (
Do you have errors, could you provide us the log?

**Comment by Rapster** [comment]
I can confirm that this command `\moderncvicons{awesome}` is messing up the generation of the PDF. If I do not include it, the rendering quite works well (except it does not include the fontawesome icons such as faExternalLink). I attached the log, you'll see weird erros starting at line 1940

**Comment by gaelfoppolo** [comment]
Hmm looks like your MikTex is broken. Could perform a full cleanup and then a fresh install?

**Comment by Rapster** [comment]
Don't think so, I just did it on my brand new laptop

**Comment by gaelfoppolo** [comment]
Worth it to try, don't you think?

**Comment by productys** [comment]
First time, I detected this issue on my Windows 7, and I have the same issue on my other laptop running under Windows 10. It's still strange to have the same issue under two different machine

**Comment by Rapster** [comment]
First time, I detected this issue on my Windows 7, and I have the same issue on my other laptop running under Windows 10. It's still strange to have the same issue under two different machine

**Comment by gaelfoppolo** [comment]
Unistall MikTex and try TeX Live. I suspect MikTex having an issue with `microtype` and `FontAwesome`.

**Comment by Rapster** [comment]
I guess you're right, there is several posts about this like this one http://tex.stackexchange.com/questions/263150/fontawesome-wont-render-correctly-while-working-on-a-moderncv, i'll try it later

**Comment by carlodri** [comment]
Works fine for me simply saying 

```latex
\usepackage{fontawesome}
```

also with `microtype`, using latest MikTeX and everything updated...

**Comment by Rapster** [comment]
Nop, i already had this package included. Does it work for you to display \faExternalLink ?

**Comment by carlodri** [comment]
@Rapster `\faExternalLink`works fine. I don't use `\moderncvicons{awesome}`, only `\usepackage{fontawesome}`

**Comment by Rapster** [comment]
Not working either, I'm using XeLatex by the way...

**Comment by carlodri** [comment]
@Rapster oh, ok, sorry I missed that point! No, I'm using `pdflatex`: that can make quite a difference I suppose.

**Comment by Rapster** [comment]
Working with pdflatex! I guess it's a problem wit XeLatex then... Thanks for your answers
